### PR TITLE
Continuation: Replace KeyValuePair with Tuples #407

### PR DESCRIPTION
**Pull request by dwnichols**
This is a pull request to fix merge conflicts and the failing examples from previous PR #407 by @isaacabraham. Locally the examples are now passing. I attempted to stay true to the previous approach.

### CODE REVIEW

**Comment by dwnichols** [comment]
The examples are passing due to the fact that each of those projects references the latest nuget package. Is the correct behaviour? I may update the references so that the HintPath points to the locally compiled version of the Adapter assembly. Any objections to that?

**Comment by isaacabraham** [comment]
Sweet!

**Comment by dwnichols** [comment]
@skaarthik : are you happy to merge, as is? I have brought up the patch coverage to just under the target. Since this PR doesn't add functionality, the failing path coverage issue is due to existing coverage problems and not untested new functionality.

**Comment by isaacabraham** [comment]
@skaarthik can you update on this?

**Comment by skaarthik** [comment]
@isaacabraham It is in my to-do list. Will review the changes in the next few days.

**Comment by skaarthik** [comment]
Changes look good to me.

@xiongrenyi @tawan0109 @danielli90 this PR changes Mobius public API and apps built using prior versions need to make minor tweak to compile if they depend on the API that is updated in this PR. Any comments?

**Comment by tawan0109** [comment]
According to the practice of Spark release, incompatible changes to public API only happen in a major version release. If we follow the same practice here, we might don't want to merge this PR to prior versions.

**Comment by skaarthik** [comment]
@tawan0109 that's correct. We will not port the changes in this PR to 1.* versions.

**Comment by dwnichols** [comment]
@skaarthik : Is this change acceptable to be merged in master and branch-2.0 then?

**Comment by skaarthik** [comment]
@dwnichols - yes, I will merge it to master and 2.0 branch.

**Comment by dwnichols** [comment]
@skaarthik : great! thank you. let me know if you run into any issues.

**Pull request merged**
