### PR TITLE
Update projects to treat warnings as errors.

### PR DESCRIPTION
**Pull request by dwnichols**
This is a code quality improvement. Treating warnings as errors
will stop warnings from getting out of hand, keeping the code base
clean and enforce the use of comments for publicly facing interfaces.

### CODE REVIEW

**Comment by dwnichols** [comment]
The build issues looks to be a problem with the external service maven. I'll trigger another build tomorrow.
```
[ERROR] Failed to execute goal on project spark-clr_2.11: Could not resolve dependencies for project com.microsoft.sparkclr:spark-clr_2.11:jar:2.0.200-SNAPSHOT: Could not transfer artifact org.scala-lang.modules:scala-xml_2.11:jar:1.0.4 from/to central (http://repo.maven.apache.org/maven2): Connect to repo.maven.apache.org:80 [repo.maven.apache.org/151.101.44.215] failed: Connection timed out (Connection timed out) -> [Help 1]
```

**Comment by skaarthik** [comment]
@dwnichols warnings-as-error flag is failing Travis build (Linux). I see `Sql/Dataset.cs(134,5): error CS1587: Warning as Error: XML comment is not placed on a valid language element` in the build log. I wonder why the build did not fail in AppVeyor (Windows).

**Comment by dwnichols** [comment]
@skaarthik : yeah, it looks like there's a difference in strictness between xbuild and msbuild.

**Comment by dwnichols** [comment]
I'm going to close this for now and do more research into whether this is possible, given we're working with both xbuild and msbuild.

**Pull request closed without merging**
