### PR TITLE
Update DynamicPartitionKafkaRDD.scala

### PR DESCRIPTION
**Pull request by xiongrenyi**
change config name spark.streaming.kafka.metadata to more meaningful mobius.streaming.kafka.CSharpReader.enabled

### CODE REVIEW

**Comment by xiongrenyi** [comment]
AppVeyor build failed with "4031Error: Could not find or load main class org.apache.spark.launcher.SparkCLRSubmitArguments ".

retrying...

**Comment by skaarthik** [comment]
LGTM

**Comment by skaarthik** [comment]
@xiongrenyi - looks like you created a dev branch on the official repo. Not sure how you ended up doing that but avoid doing that in the future. The dev branch should be in your repo.

**Comment by xiongrenyi** [comment]
I chose to make the change in place since it's minor, in which case GitHub has the option to create a pull request by creating a temp branch automatically.

**Comment by xiongrenyi** [comment]
anyway, the PR's checks failed with following error, any idea?

4029[RunSamples.cmd] call sparkclr-submit.cmd --exe SparkCLRSamples.exe C:\projects\sparkclr\build\localmode\..\runtime\samples spark.local.dir C:\projects\sparkclr\build\localmode\..\runtime\Temp sparkclr.sampledata.loc C:\projects\sparkclr\build\localmode\..\runtime\data --validate
 4030SPARKCLR_JAR=spark-clr_2.10-1.6.1-SNAPSHOT.jar 
 4031Error: Could not find or load main class org.apache.spark.launcher.SparkCLRSubmitArguments

**Pull request merged**
