### PR TITLE
Fix needless quotes to arguments (well on Spark 1.6 but causes "input line too long" error on Spark 2.0).

### PR DESCRIPTION
**Pull request by qualiu**
Fix needless quotes to arguments (well on Spark 1.6 but causes "input line too long" error on Spark 2.0).
   
Error repro : (quotes "Pi*" cause error)
    set HADOOP_HOME=d:\msgit\skaarthikMobius\build\tools\winutils
    set SPARKCLR_HOME=d:\msgit\skaarthikMobius\build\runtime
    set SPARK_HOME=d:\msgit\skaarthikMobius\build\tools\spark-2.0.0-preview-bin-hadoop2.6
    cd /d d:\msgit\skaarthikMobius\build\runtime\samples
    %SPARKCLR_HOME%\scripts\sparkclr-submit.cmd --exe SparkCLRSamples.exe %CD% --torun Pi* --data d:\tmp\skdata

### CODE REVIEW

**Comment by qualiu** [comment]
Repro “**The input line is too long**” error from Spark 2.0 to Spark-1.6  is simple : 
Copy, Paste to run following commands  (just change the first line **_d:\msgit\lzMobius_** to yours )
```
set MOBIUS_CODE_ROOT=d:\msgit\lzMobius
set SPARK_HOME=%MOBIUS_CODE_ROOT%\build\tools\spark-1.6.1-bin-hadoop2.6
set HADOOP_HOME=%MOBIUS_CODE_ROOT%\build\tools\winutils
set SPARKCLR_HOME=%MOBIUS_CODE_ROOT%\build\runtime
cd /d %SPARKCLR_HOME%\samples
%SPARKCLR_HOME%\scripts\sparkclr-submit.cmd --exe SparkCLRSamples.exe %CD% --torun Pi* --data d:\tmp\skdata%SPARKCLR_HOME%\scripts\sparkclr-submit.cmd --exe SparkCLRSamples.exe %CD% --torun Pi* --data d:\tmp\skdata

```

①**To repro it, add quotes** just like Spark-2.0  by following command (you can also modify the file manually) :
`lzmw -p %MOBIUS_CODE_ROOT%\build\tools\spark-1.6.1-bin-hadoop2.6\bin\spark-submit.cmd -t "(%~dp0spark-submit2.cmd)" -o "\"$1\"" -R`
Then run the **last submit command** again, you’ll got the error : “**The input line is too long**”.

②**To restore it back** (eliminate the error) :
`lzmw -p %MOBIUS_CODE_ROOT%\build\tools\spark-1.6.1-bin-hadoop2.6\bin\spark-submit.cmd -t "\"(%~dp0spark-submit2.cmd)\"" -o "$1" -R
`
lzmw is a standalone exe (versions : Windows/Cygwin/CentOS/Ubuntu/Fedora) : search "lzshare" in OneNote.

**Comment by qualiu** [comment]
Repro “**The input line is too long**” error from Spark 2.0 to Spark-1.6  is simple : 
Copy, Paste to run following commands  (just change the first line **_d:\msgit\lzMobius_** to yours )
```
set MOBIUS_CODE_ROOT=d:\msgit\lzMobius
set SPARK_HOME=%MOBIUS_CODE_ROOT%\build\tools\spark-1.6.1-bin-hadoop2.6
set HADOOP_HOME=%MOBIUS_CODE_ROOT%\build\tools\winutils
set SPARKCLR_HOME=%MOBIUS_CODE_ROOT%\build\runtime
cd /d %SPARKCLR_HOME%\samples
%SPARKCLR_HOME%\scripts\sparkclr-submit.cmd --exe SparkCLRSamples.exe %CD% --torun Pi* --data "%tmp%\pidata"
```

①**To repro it, add quotes** just like Spark-2.0  by following command (you can also modify the file manually) :
`lzmw -p %MOBIUS_CODE_ROOT%\build\tools\spark-1.6.1-bin-hadoop2.6\bin\spark-submit.cmd -t "(%~dp0spark-submit2.cmd)" -o "\"$1\"" -R`
Then run the **last submit command** again, you’ll got the error : “**The input line is too long**”.

②**To restore it back** (eliminate the error) :
`lzmw -p %MOBIUS_CODE_ROOT%\build\tools\spark-1.6.1-bin-hadoop2.6\bin\spark-submit.cmd -t "\"(%~dp0spark-submit2.cmd)\"" -o "$1" -R
`

lzmw is a standalone exe (versions : Windows/Cygwin/CentOS/Ubuntu/Fedora) : search "lzshare" in internal OneNote.

**Comment by qualiu** [comment]
Repro “**The input line is too long**” error from Spark 2.0 to Spark-1.6  is simple : 
Copy, Paste to run following commands  (just change the first line **_d:\msgit\lzMobius_** to yours )
```
set MOBIUS_CODE_ROOT=d:\msgit\lzMobius
set SPARK_HOME=%MOBIUS_CODE_ROOT%\build\tools\spark-1.6.1-bin-hadoop2.6
set HADOOP_HOME=%MOBIUS_CODE_ROOT%\build\tools\winutils
set SPARKCLR_HOME=%MOBIUS_CODE_ROOT%\build\runtime
cd /d %SPARKCLR_HOME%\samples
%SPARKCLR_HOME%\scripts\sparkclr-submit.cmd --exe SparkCLRSamples.exe %CD% --torun Pi* --data "%tmp%\pidata"
```

①**To repro it, add quotes** just like Spark-2.0  by following command (you can also modify the file manually) :
`lzmw -p %MOBIUS_CODE_ROOT%\build\tools\spark-1.6.1-bin-hadoop2.6\bin\spark-submit.cmd -t "(%~dp0spark-submit2.cmd)" -o "\"$1\"" -R`
Then run the **last submit command** again, you’ll got the error : “**The input line is too long**”.

②**To restore it back** (eliminate the error) :
`lzmw -p %MOBIUS_CODE_ROOT%\build\tools\spark-1.6.1-bin-hadoop2.6\bin\spark-submit.cmd -t "\"(%~dp0spark-submit2.cmd)\"" -o "$1" -R
`

lzmw is a standalone exe (versions : Windows/Cygwin/CentOS/Ubuntu/Fedora) : search "lzshare" in internal OneNote.

**Comment by danielli90** [comment]
LGTM.

Thanks  @qualiu. After merging this PR to Mobius, we should file a JIRA for Apache Spark, and fix spark-submit.cmd by removing quotes.

**Comment by qualiu** [comment]
@skaarthik @qintao1976 @tawan0109 
Please give your comments and tell me if I merge this.
**And it has 7 commits record for this 1 file change, will this garbage 6 commit records merged into main?  Should I create a clean pull request ?**

**Comment by skaarthik** [comment]
@qualiu - I already signed off on CodeFlow. So, unless there are open questions/comments from others, you could merge this PR.

When you try to merge, you will see an option to "squash and merge". Use that option (instead of "create merge commit") and your commit history will not get pushed to the official repo.

**Pull request merged**
