### PR TITLE
Merge bug fix from master to Branch-1.6

### PR DESCRIPTION
**Pull request by qintao1976**
Merge the following bug fix to branch1.6: (1) renyi's fix of CSharpDStream, (2) ReduceByWindowAndKey fix

### CODE REVIEW

**Comment by skaarthik** [comment]
Can we merge all changes from master to branch 1.6 instead of selected changes?

**Comment by qintao1976** [comment]
There are two reasons:
1) Although originated from the same parent, now Master branch and branch-1.6 are diverse. I have tried to merge all changes from master, but failed due to conflict.
2) In main branch, there are some break change. For example, the time unit of duration for StreamingContext has changed from milliseconds to seconds.

**Comment by qintao1976** [comment]
Maven download failure for the first Appveyor build:

[downloadtools.Download-File] Download completed. Time taken: 515 milliseconds
[downloadtools.Untar-File] Extracting C:\projects\sparkclr\build\localmode\..\tools\apache-maven-3.3.3-bin.tar.gz to C:\projects\sparkclr\build\localmode\..\tools ...
Error extracting C:\projects\sparkclr\build\localmode\..\tools\apache-maven-3.3.3-bin.tar.gz 
Exception message EOS reading GZIP header

**Comment by skaarthik** [comment]
We have to do it eventually anyways at the end of M3. So, I suggest doing it now. We should just take master changes and overwrite any conflicts in 1.6 branch (most likely the conflicts are in version references). We should document the behavior change in streaming API - it is a bug fix after all.

**Comment by danielli90** [comment]
1.6 branch  is snapped to Spark 1.6.1. The master branch is snapped to Spark 1.6.2. Are these break changes " the time unit of duration for StreamingContext has changed from milliseconds to seconds" introduced in Spark 1.6.2? If yes, we may need to keep 1.6 branch aligned with Spark 1.6.1 as-is (and keep the master branch aligned with Spark 1.6.2)

**Comment by skaarthik** [comment]
Master will switch to Spark 2.0 soon. Going with what Spark is doing let's keep 1.6 branch for all Spark 1.6.* releases. In the worst  case we could overload the millisecond API in 1.6 branch for the change made recently and keep the old behavior intact. We can introduce the breaking change in Mobius 2.0.0 release.

**Comment by qintao1976** [comment]
I don't think the change of time unit is introduced by Spark 1.6.2. I think it is only change in C# side. But I am not sure. Perhaps renyi knows the reason. Thanks

**Comment by xiongrenyi** [comment]
Time unit from milliseconds to seconds is actually a bug fix to align with both Scala and python.

**Comment by xiongrenyi** [comment]
LGTM

**Comment by skaarthik** [comment]
Per the discussion offline, let's revert the change to batchwindow in SteamingContext in master branch and bring in all changes from master to branch-1.6. We can then do a release in branch-1.6.

**Comment by qintao1976** [comment]
Close this PR because we need to merge all changes from master to branch-1.6. Need to create a new PR.

**Pull request closed without merging**
