### PR TITLE
Fix for issue #285

### PR DESCRIPTION
**Pull request by kai-zeng**
This PR mainly contains two changes for Linux:
1. Fix CSharpWorker path, by adding "./"
2. Preserve file permissions when doing zip & unzip dependencies

### CODE REVIEW

**Comment by kai-zeng** [comment]
BTW, CSharpWorker.exe downloaded from nuget does not have executable permission on Linux. We need to fix this @skaarthik

**Comment by skaarthik** [comment]
@kai-zeng we can fix the permissions of CSharpWorker.exe in NuGet before the next release. For the past releases, I am wondering if we could have a special check in place just for CSharpWorker.exe at the time of unzipping and set the write permissions if needed. I believe that would take care of YARN mode execution in Linux. For local and standalone modes in Linux, where zipping/unzipping is not done, we could document the requirement to update the permissions of CSharpWorker.exe in the resources folder before app submission.

**Comment by kai-zeng** [comment]
ping... 
@skaarthik 
@tawan0109

**Comment by kai-zeng** [comment]
@skaarthik Sure. We can add that check to branch 1.5 and 1.6. I think for master we don't that check

**Comment by skaarthik** [comment]
@kai-zeng - example projects in master branch point to the last release (1.6.100) in NuGet that does not have the right permissions for CSharpWorker.exe. So, I am not sure why you think the check is not necessary in master branch. Am I missing something?

**Comment by kai-zeng** [comment]
@skaarthik I thought example projects in our master branch is referencing a daily snapshot package. If it references release 1.6.1, then we do need the check.
BTW, shouldn't example projects reference a daily built package?

**Comment by skaarthik** [comment]
@kai-zeng NuGet is not good for publishing daily snapshot builds. Guan was exploring myget.org for that. I do not know where it landed. We were also hoping that example projects would serve as templates for developers to start building their Mobius apps.

It is a topic that needs further discussion. So, let's continue this conversation outside the PR. I hope you are fine with the idea of updating permissions in master also along with other branches.

**Comment by kai-zeng** [comment]
@skaarthik Sure. I will add the check.

**Comment by skaarthik** [comment]
Thanks @kai-zeng 
LGTM

**Pull request merged**
