### PR TITLE
Add Python version performance benchmark test; Add usage and example and RIOSocket option support for C# version benchmark; Update Scala version benchmark; Update csv package version.

### PR DESCRIPTION
**Pull request by qualiu**
Besides normal spark-submit , there's a convenient way using https://github.com/qualiu/testMobius
**1.Cluster mode examples as following:**
```
D:\msgit\lqmMobius\testMobius\scripts\perf\submit-python-perf-test.bat d:\msgit\lqmMobius\python\perf 10 hdfs:///perf/data/deletions/*
D:\msgit\lqmMobius\testMobius\scripts\perf\submit-scala-perf-test.bat  d:\msgit\lqmMobius\scala\perf  10
D:\msgit\lqmMobius\testMobius\scripts\perf\submit-mobius-perf-test.bat d:\msgit\lqmMobius\csharp\perf 10

```

**2.Local mode examples :**
(1) First set SparkOptions : just copy the "Local Mode set SparkOptions=" after running the bat without arguments.
(2) Then submit local test : (you should have downloaded or copied the test data, like d:\mobius\deletions)
```
D:\msgit\lqmMobius\testMobius\scripts\perf\submit-python-perf-test.bat d:\msgit\lqmMobius\python\perf 3 d:\mobius\deletions\deletions.csv-00000-of-00020
D:\msgit\lqmMobius\testMobius\scripts\perf\submit-scala-perf-test.bat  d:\msgit\lqmMobius\scala\perf  3 d:\mobius\deletions\deletions.csv-00000-of-00020
D:\msgit\lqmMobius\testMobius\scripts\perf\submit-mobius-perf-test.bat d:\msgit\lqmMobius\csharp\perf 3 d:\mobius\deletions\deletions.csv-00000-of-00020

```

### CODE REVIEW

**Comment by dwnichols** [comment]
@qualiu : You have bumped the version of the commons-csv and spark-csv dependencies. I noticed that this was only done within within the windows build. Can you make that change for the linux build. The two should always be kept in line with one another. Here's the file and line number:

https://github.com/Microsoft/Mobius/blob/master/build/build.sh#L33

**Comment by qualiu** [comment]
@dwnichols : Thanks ! 
I've updated the Linux shells in my latest commit : [build/build.sh](https://github.com/qualiu/Mobius/blob/lzperf-master/build/build.sh#L33)  and [build/localmode/run-samples.sh](https://github.com/qualiu/Mobius/blob/lzperf-master/build/localmode/run-samples.sh#L77)

( Invisible in Mobius master right now : [build/build.sh](https://github.com/Microsoft/Mobius/blob/master/build/build.sh#L33)  and [build/localmode/run-samples.sh](https://github.com/Microsoft/Mobius/blob/master/build/localmode/run-samples.sh#L77) )

**Comment by qualiu** [comment]
### 1. Validation on Windows
Assuming your local Mobius code root = `d:\msgit\lqmMobius`
Besides normal `spark-submit` (like following Linux validation), you can use [testMobius](https://github.com/qualiu/testMobius/tree/master/scripts/perf)\scripts\perf

```
cd /d d:\msgit\lqmMobius
git clone https://github.com/qualiu/testMobius

Set SparkOptions : just copy " Local Mode : set SparkOptions=***" by running  testMobius\scripts\perf\submit-mobius-perf-test.bat

testMobius\scripts\perf\submit-mobius-perf-test.bat csharp\perf 1 d:\mobius\deletions\deletions.csv-00000-of-00020
testMobius\scripts\perf\submit-python-perf-test.bat python\perf 1 d:\mobius\deletions\deletions.csv-00000-of-00020
testMobius\scripts\perf\submit-scala-perf-test.bat scala\perf 1 d:\mobius\deletions\deletions.csv-00000-of-00020

```
Results like:
```
2016-09-20 10:38:42 CST Python version: Run count = 1, all median time costs[4] : RunDFLineCount=5; RunDFMaxDeletionsByUser=11; RunRDDLineCount=9; RunRDDMaxDeletionsByUser=16
2016-09-20 11:30:23 CST C# version: Run count = 1, all median time costs[4] : RunDFLineCount=1; RunDFMaxDeletionsByUser=13; RunRDDLineCount=0; RunRDDMaxDeletionsByUser=9
2016-09-20 10:37:22 CST Scala version: Run count = 1, all median time costs[4]: RunDFLineCount=7; RunDFMaxDeletionsByUser=10; RunRDDLineCount=0; RunRDDMaxDeletionsByUser=15

```

### 2. Validation on Linux (CentOS 7.0)
Assuming your local Linux Mobius code root = `/diskExt/msgit/lqmMobius`
If cannot run exe without mono prefix , try root executing: <br> `echo ':CLR:M::MZ::/usr/bin/mono:' > /proc/sys/fs/binfmt_misc/register`

```
$HADOOP_HOME/sbin/start-all.sh
cd /diskExt/msgit/lqmMobius

$SPARK_HOME/bin/spark-submit  --total-executor-cores 8 --executor-memory 8G --jars $PWD/build/runtime/dependencies/commons-csv-1.4.jar,$PWD/build/runtime/dependencies/spark-csv_2.10-1.4.0.jar  --conf spark.sql.warehouse.dir=/tmp/perf-warehouse $PWD/python/perf/spark-python-perf.py 1 file:///diskExt/deletions.csv-00000-of-00020

$SPARK_HOME/bin/spark-submit  --total-executor-cores 8 --executor-memory 8G --jars $PWD/build/runtime/dependencies/commons-csv-1.4.jar,$PWD/build/runtime/dependencies/spark-csv_2.10-1.4.0.jar  --conf spark.sql.warehouse.dir=/tmp/perf-warehouse --class com.microsoft.spark.csharp.PerfBenchmark scala/perf/target/spark-clr-perf-2.0.0-SNAPSHOT.jar 1 file:///diskExt/deletions.csv-00000-of-00020

export SPARKCLR_HOME=$PWD/build/runtime
$SPARKCLR_HOME/scripts/sparkclr-submit.sh --total-executor-cores 8 --executor-memory 8G --jars $PWD/build/runtime/dependencies/commons-csv-1.4.jar,$PWD/build/runtime/dependencies/spark-csv_2.10-1.4.0.jar  --conf spark.sql.warehouse.dir=/tmp/perf-warehouse --exe SparkCLRPerf.exe $PWD/csharp/Perf/Microsoft.Spark.CSharp/bin/Release file:///tmp/PerfMobius 1 file:///diskExt/deletions.csv-00000-of-00020

```

Results like:
```
2016-09-20 11:28:02 CST Scala version: Run count = 1, all median time costs[4]: RunDFLineCount=1; RunDFMaxDeletionsByUser=15; RunRDDLineCount=0; RunRDDMaxDeletionsByUser=2
2016-09-20 11:20:44 C Python version: Run count = 1, all median time costs[4] : RunDFLineCount=7; RunDFMaxDeletionsByUser=10; RunRDDLineCount=5; RunRDDMaxDeletionsByUser=6
2016-09-20 11:34:06 C C# version: Run count = 1, all median time costs[4] : RunDFLineCount=1; RunDFMaxDeletionsByUser=11; RunRDDLineCount=0; RunRDDMaxDeletionsByUser=13

```

**Comment by qualiu** [comment]
### 1. Validation on Windows (Local mode)
Assuming your local Mobius code root = `d:\msgit\lqmMobius`
Besides normal `spark-submit` (like following Linux validation), you can use [testMobius](https://github.com/qualiu/testMobius/tree/master/scripts/perf)\scripts\perf

```
cd /d d:\msgit\lqmMobius
git clone https://github.com/qualiu/testMobius

Set SparkOptions : just copy " Local Mode : set SparkOptions=***" by running  testMobius\scripts\perf\submit-mobius-perf-test.bat

testMobius\scripts\perf\submit-mobius-perf-test.bat csharp\perf 1 d:\mobius\deletions\deletions.csv-00000-of-00020
testMobius\scripts\perf\submit-python-perf-test.bat python\perf 1 d:\mobius\deletions\deletions.csv-00000-of-00020
testMobius\scripts\perf\submit-scala-perf-test.bat scala\perf 1 d:\mobius\deletions\deletions.csv-00000-of-00020

```
Results like:
```
2016-09-20 10:38:42 CST Python version: Run count = 1, all median time costs[4] : RunDFLineCount=5; RunDFMaxDeletionsByUser=11; RunRDDLineCount=9; RunRDDMaxDeletionsByUser=16
2016-09-20 11:30:23 CST C# version: Run count = 1, all median time costs[4] : RunDFLineCount=1; RunDFMaxDeletionsByUser=13; RunRDDLineCount=0; RunRDDMaxDeletionsByUser=9
2016-09-20 10:37:22 CST Scala version: Run count = 1, all median time costs[4]: RunDFLineCount=7; RunDFMaxDeletionsByUser=10; RunRDDLineCount=0; RunRDDMaxDeletionsByUser=15

```

### 2. Validation on Linux (CentOS 7.0) (Local mode)
Assuming your local Linux Mobius code root = `/diskExt/msgit/lqmMobius`
If cannot run exe without mono prefix , try root executing: <br> `echo ':CLR:M::MZ::/usr/bin/mono:' > /proc/sys/fs/binfmt_misc/register`

```
$HADOOP_HOME/sbin/start-all.sh
cd /diskExt/msgit/lqmMobius

$SPARK_HOME/bin/spark-submit  --total-executor-cores 8 --executor-memory 8G --jars $PWD/build/runtime/dependencies/commons-csv-1.4.jar,$PWD/build/runtime/dependencies/spark-csv_2.10-1.4.0.jar  --conf spark.sql.warehouse.dir=/tmp/perf-warehouse $PWD/python/perf/spark-python-perf.py 1 file:///diskExt/deletions.csv-00000-of-00020

$SPARK_HOME/bin/spark-submit  --total-executor-cores 8 --executor-memory 8G --jars $PWD/build/runtime/dependencies/commons-csv-1.4.jar,$PWD/build/runtime/dependencies/spark-csv_2.10-1.4.0.jar  --conf spark.sql.warehouse.dir=/tmp/perf-warehouse --class com.microsoft.spark.csharp.PerfBenchmark scala/perf/target/spark-clr-perf-2.0.0-SNAPSHOT.jar 1 file:///diskExt/deletions.csv-00000-of-00020

export SPARKCLR_HOME=$PWD/build/runtime
$SPARKCLR_HOME/scripts/sparkclr-submit.sh --total-executor-cores 8 --executor-memory 8G --jars $PWD/build/runtime/dependencies/commons-csv-1.4.jar,$PWD/build/runtime/dependencies/spark-csv_2.10-1.4.0.jar  --conf spark.sql.warehouse.dir=/tmp/perf-warehouse --exe SparkCLRPerf.exe $PWD/csharp/Perf/Microsoft.Spark.CSharp/bin/Release file:///tmp/PerfMobius 1 file:///diskExt/deletions.csv-00000-of-00020

```

Results like:
```
2016-09-20 11:28:02 CST Scala version: Run count = 1, all median time costs[4]: RunDFLineCount=1; RunDFMaxDeletionsByUser=15; RunRDDLineCount=0; RunRDDMaxDeletionsByUser=2
2016-09-20 11:20:44 C Python version: Run count = 1, all median time costs[4] : RunDFLineCount=7; RunDFMaxDeletionsByUser=10; RunRDDLineCount=5; RunRDDMaxDeletionsByUser=6
2016-09-20 11:34:06 C C# version: Run count = 1, all median time costs[4] : RunDFLineCount=1; RunDFMaxDeletionsByUser=11; RunRDDLineCount=0; RunRDDMaxDeletionsByUser=13

```

**Comment by skaarthik** [comment]
@dwnichols - good catch. Thanks.
@qualiu - push spark-csv version changes to branch-1.6 as well

**Comment by qualiu** [comment]
@skaarthik : pull request to branch-1.6 : https://github.com/Microsoft/Mobius/pull/566

**Pull request merged**
