### PR TITLE
Merge two code coverage uploads to one

### PR DESCRIPTION
**Pull request by hebinhuang**

### CODE REVIEW

**Comment by skaarthik** [comment]
@hebinhuang is it possible to report C#, C++ and Scala code coverage numbers separately instead of rolling everything under one number for the project? In other words, can we have three different codecov badges in our repo each for different language?

**Comment by hebinhuang** [comment]
@skaarthik I have tried different ways. It is not possible to separate the number by languages, no matter how many times of uploading in one build of appveyor. 

Let me do some research.

**Comment by hebinhuang** [comment]
@skaarthik CodeCov do merge multiple uploads with different coverage data for a single build.

https://github.com/codecov/support/issues/132

**Comment by skaarthik** [comment]
LGTM

**Pull request merged**
