### PR TITLE
Replace KeyValuePair with Tuples

### PR DESCRIPTION
**Pull request by isaacabraham**
An example replacement of KVPs with Tuples as discussed in #340. It enables code that looks like this: -

``` fsharp
let lines = sparkContext.TextFile filePath
let counts =
   lines.FlatMap(fun x -> x.Split ' ' :> _)
        .Map(fun w -> KeyValuePair(w, 1))
        .ReduceByKey(fun x y -> x + y)
        .Collect()
for count in counts do
   printfn "%s: %d" count.Key count.Value
```

to be replaced with this

``` fsharp
let lines = sparkContext.TextFile filePath
let counts =
   lines.FlatMap(fun x -> x.Split ' ' :> _)
        .Map(fun w -> w, 1)
        .ReduceByKey(fun x y -> x + y)
        .Collect()
for (key, value) in counts do
   printfn "%s: %d" key value
```

as well as all the other usual things like `fst` and `snd` etc. etc.

### CODE REVIEW

**Comment by isaacabraham** [comment]
Any thoughts on this PR?

**Comment by skaarthik** [comment]
@isaacabraham - following samples (also used as functional tests) are failing in this PR (output of RunSamples.cmd copied below)
``` 
* SparkContextAccumulatorSample (category: default), duration=00:00:04.2144522
* RDDTreeReduceSample (category: default), duration=00:00:00.9291795
* RDDCountByValueSample (category: default), duration=00:00:02.5838769
* PairRDDCountByKeySample (category: default), duration=00:00:02.1073810
* DFForeachSample (category: default), duration=00:00:00.9013544
* DFForeachPartitionSample (category: default), duration=00:00:02.2719630
``` 
I see the following test output printed to console for PairRDDCountByKeySample. Looks like wrong type is used in the assert statement.

``` 
---- Error running sample PairRDDCountByKeySample (duration=00:00:02.1073810) -----
System.Reflection.TargetInvocationException: Exception has been thrown by the target of an invocation. ---> NUnit.Framework.AssertionException:   Expected: 2
  But was:  < <(a, 2)> >
 
   at NUnit.Framework.Assert.That[TActual](TActual actual, IResolveConstraint expression, String message, Object[] args)
   at Microsoft.Spark.CSharp.Samples.PairRDDSamples.PairRDDCountByKeySample() in c:\projects\sparkclr\csharp\Samples\Microsoft.Spark.CSharp\PairRDDSamples.cs:line 122
   --- End of inner exception stack trace ---
   at System.RuntimeMethodHandle.InvokeMethod(Object target, Object[] arguments, Signature sig, Boolean constructor)
   at System.Reflection.RuntimeMethodInfo.UnsafeInvokeInternal(Object obj, Object[] parameters, Object[] arguments)
   at System.Reflection.RuntimeMethodInfo.Invoke(Object obj, BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Spark.CSharp.Samples.SamplesRunner.RunSample(MethodInfo sample) in c:\projects\sparkclr\csharp\Samples\Microsoft.Spark.CSharp\SamplesRunner.cs:line 79
``` 

Try running these examples that are failing using the instructions at https://github.com/Microsoft/Mobius/blob/master/notes/windows-instructions.md#running-in-local-mode-dev-environment and fix the failures.

Once all the tests are passing, I will run perf tests on this PR as discussed in https://github.com/Microsoft/Mobius/issues/340. Once that passes, this PR will be ready for merge as a part of upgrade to Spark 2.0 (since it changes public API).

**Comment by isaacabraham** [comment]
@skaarthik Thanks for looking at this. I'm not in a position to fix this at the moment (the machine with Spark etc. installed isn't here) and won't be for at least a week or so - would you mind looking at this as it seems that you've already identified the issue? Thanks!

**Comment by skaarthik** [comment]
@isaacabraham - sure. I only looked at the failure in one test. Will take a look at other test failures & possibly push a fix when I get a chance.

**Comment by skaarthik** [comment]
I looked at other test failures - some are due to wrong types (need to be updated to reflect the changes in this PR) and some are due to mismatch in expected and actual values that need deeper investigation. I will do the investigation later.

**Comment by skaarthik** [comment]
Anyone interested in picking this up, resolve conflicts and fix failing tests?

**Comment by isaacabraham** [comment]
I will *try* to - can't commit to any time at the moment - but please leave this PR open :-)

**Comment by skaarthik** [comment]
@isaacabraham - this PR will remain open. I will also try to find time to get this PR updated.

**Pull request merged**
