### PR TITLE
Add CSharpInputDStream to enable control of data injection by C# code

### PR DESCRIPTION
**Pull request by qintao1976**
Add CSharpInputDStream to enable control of data injection by C# code

### CODE REVIEW

**Comment by qintao1976** [comment]
Code coverage in Scala side:

before:
image

after:
image

**Comment by danielli90** [comment]
@xiongrenyi and @tawan0109, can you help review this PR?

**Comment by tawan0109** [comment]
LGTM

**Comment by qualiu** [comment]
LGTM

**Comment by xiongrenyi** [comment]
LGTM

thought same thing can be achieved by ConstantInputStream plus MapPartitionsWithIndex. but  batch timestamp is not supported in mapFunc which is needed here.

**Comment by skaarthik** [comment]
@qintao1976 I noticed that doing code coverage measurement for org.apache.spark is not a good approach for us because it counts the coverage on unit test code as 100% and providing a misleading overall cc metric. Can you break up the code coverage measurement to include only non-test code or the classes that you are updating?

**Comment by qintao1976** [comment]
before:
image

after:
image

**Pull request merged**
