### PR TITLE
add new API DirectKafkaStreamWithRepartition manual test only in Sandbox

### PR DESCRIPTION
**Pull request by xiongrenyi**
customizing KafkaUtils using inheritance model with dynamic kafka rdd partitioning and kafka read fault tolerance. no automated tests yet

### CODE REVIEW

**Comment by skaarthik** [comment]
We need unit test for C# code to make sure code cov % does not drop.

Can we also get unit tests for the scala code from Spark tree and reuse them for the custom implementation?

**Comment by xiongrenyi** [comment]
unit test added initially for the new direct kafka API like the existing one, it's the proxy code (not covered in unit test) which drops the cov %

**Comment by xiongrenyi** [comment]
want to unblock people, so only manual testing for now

**Comment by xiongrenyi** [comment]
added sample (functional test) as a separately

**Pull request merged**
