### PR TITLE
Implement automatic code coverage reports for c++ code

### PR DESCRIPTION
**Pull request by hebinhuang**
Using Dynamic Code Coverage Tools of Visual Studio to generate C++ code coverage reports in CodeCov.io.

Limitation:
Currently, CodeCov can supports the reports generated by Dynamic Code Coverage Tools of Visual Studio with only one module. CodeCov is working on the fix to support multiple modules in the reports. In the meanwhile, CodeCov is also working on to support the reports generated by vstest.consle.exe with /enablecodecoverage parameter.
Please see [https://github.com/codecov/support/issues/255] for more information.

### CODE REVIEW

**Comment by hebinhuang** [comment]
The coverage number got decreased, because it includes the C++ coverage.
codecover

**Comment by danielli90** [comment]
LGTM

**Comment by skaarthik** [comment]
What is the extra latency in build time introduced with C++ code cov?

**Comment by hebinhuang** [comment]
@skaarthik, it introduced another full unit tests run.

**Comment by skaarthik** [comment]
LGTM

**Pull request merged**
